## Tu primera matriz Numpy

En este capítulo, vamos a sumergirnos en el mundo del béisbol. En el camino, te sentirás cómodo con los conceptos básicos de *numpy* un poderoso paquete para hacer ciencia de datos.

*baseball* Ya se ha definido una lista en el script de Python, que representa la altura de algunos jugadores de béisbol en centímetros. ¿Puedes agregar algún código aquí y allá para crear una matriz *numpy* a partir de él?

**Actividad**

* Importe el paquete numpy como np, para que pueda consultar *numpy* con *np*.
* Use **np.array()** para crear una matriz *numpy* desde baseball. Nombra esta matriz *np_baseball*.
* Imprima el tipo de *np_baseball* para verificar que lo hizo bien.

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


## Altura de los jugadores de beisbol

Eres un gran fanático del béisbol. Decides llamar a la MLB (Major League Baseball) y pedir más estadísticas sobre la altura de los jugadores principales. Pasan a lo largo de datos de más de un millar de jugadores, que se almacena como una lista regular de Python: *height_in*. La altura se expresa en pulgadas. ¿Puedes hacer una numpymatriz y convertir las unidades a metros?

*height_in* ya está disponible y el paquete *numpy* está cargado, por lo que puede comenzar de inmediato (Fuente: stat.ucla.edu ).

**Actividad**

* Crea una matriz *numpy* a partir de *height_in*. Nombra esta nueva matriz *np_height_in*.
* Imprimir *np_height_in*.
* Multiplique *np_height_in* con *0.0254* para convertir todas las medidas de altura de pulgadas a metros. Almacenar los nuevos valores en una nueva matriz, *np_height_m*.
* Imprima *np_height_my* compruebe si la salida tiene sentido.

In [26]:
# height is available as a regular list
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
height_in =df['Height(inches)']

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


## IMC del jugador de béisbol

La MLB también ofrece permitirle analizar sus datos de peso. Nuevamente, ambos están disponibles como listas regulares de Python: height_iny weight_lb. *height_in* está en pulgadas y *weight_lb* está en libras.

Ahora es posible calcular el IMC de cada jugador de béisbol. El código de Python para convertir *height_in* a una matriz *numpy* con las unidades correctas ya está disponible en el espacio de trabajo. ¡Sigue las instrucciones paso a paso y termina el juego!

* Cree una matriz *numpy* de la lista *weight_lb* con las unidades correctas. Multiplique por *0.453592* para pasar de libras a kilogramos. Almacene la matriz *numpy* resultante como *np_weight_kg*.

* Use *np_height_m* y *np_weight_kg* para calcular el IMC de cada jugador. Use la siguiente ecuación:

$$\text{IMC}=\frac{Peso (Kg)}{Altura (m^2)}$$


* Guarde la matriz *numpy* resultante como *bmi*.

* Imprimir *bmi*.

In [30]:
# height and weight are available as regular lists
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
height_in = df['Height(inches)']
weight_lb = df['Weight(pounds)']

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/(np_height_m**2)

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


## Jugadores de béisbol ligeros

Para subconjuntar tanto las listas como las matrices *numpy* de Python normales , puede usar corchetes:

**x = [4 , 9 , 6, 3, 1]  
x[1]  
import numpy as np  
y = np.array(x)  
y[1]**

Para concreto *numpy*, también se puede usar booleanas matrices *numpy*:

**high = y > 5
y[high]**

El código que calcula el IMC de todos los jugadores de béisbol ya está incluido. ¡Sigue las instrucciones y revela cosas interesantes de los datos!

**Actividad**

* Cree una matriz *numpy* booleana : el elemento de la matriz debería ser *True* si el IMC del jugador de béisbol correspondiente está por debajo de 21. Puede usar el operador **<** para esto. Nombra la matriz *light*.
* Imprime la matriz *light*.
* Imprima una matriz *numpy* con los IMC de todos los jugadores de béisbol cuyo IMC es inferior a 21. Use corchetes dentro de *light* para hacer una selección en la matriz *bmi*.

In [40]:
# height and weight are available as a regular lists
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
height_in = list(df['Height(inches)'])
weight_lb = list(df['Weight(pounds)'])

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


C:\Users\dnajar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in less
  app.launch_new_instance()


## Efectos secundarios de NumPy


En primer lugar, las matrices numpy no pueden contener elementos con diferentes tipos. Si intenta crear una lista de este tipo, algunos de los tipos de elementos se cambian para terminar con una lista homogénea. Esto se conoce como coerción de tipo.

En segundo lugar, los operadores aritméticos típicos, tales como **+, -, * y /** tienen un significado diferente para las listas y  de Python matrices numpy regulares.

Echa un vistazo a esta línea de código:

**np.array([True, 1, 2]) + np.array([3, 4, False])**

¿Puedes decir qué fragmento de código construye exactamente el mismo objeto Python? El paquete numpy ya está importado como np, por lo que puede comenzar a experimentar en el Shell de IPython de inmediato.

Respuestas posibles
* np.array([True, 1, 2, 3, 4, False])
* np.array([4, 3, 0]) + np.array([0, 2, 2])
* np.array([1, 1, 2]) + np.array([3, 4, -1])
* np.array([0, 1, 2, 3, 4, 5])

## Subconjunto de matrices Numpy

Lo has visto con tus propios ojos: las listas y matrices numpy de Python a veces se comportan de manera diferente. Afortunadamente, todavía hay certezas en este mundo. Por ejemplo, el subconjunto (usando la notación de corchetes en listas o matrices) funciona exactamente igual. Para ver esto usted mismo, pruebe las siguientes líneas de código en el Shell de IPython:

x = ["a", "b", "c"]  
x[1]  

np_x = np.array(x)
np_x[1]  

La secuencia de comandos a la derecha ya contiene código que las importaciones *numpy* como *np*, y almacena tanto la altura y el peso de los jugadores de la MLB como matrices *numpy*.

**Actividad**
* Subconjunto *np_weight_lb* imprimiendo el elemento en el índice 50.
* Imprima una sub-matriz *np_height_in* que contenga los elementos en el índice 100 hasta el índice 110 **inclusive**.

In [42]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

195.0
[73 72 74 73 74 72 73 69 72 73 75]
