## Tu primera matriz 2D NumPy

Antes de trabajar en los datos reales de MLB, intentemos crear una matriz 2D *numpy* a partir de una pequeña lista de listas.

En este ejercicio, baseball hay una lista de listas. La lista principal contiene 4 elementos. Cada uno de estos elementos es una lista que contiene la altura y el peso de 4 jugadores de béisbol, en este orden. baseball ya está codificado para usted en el guión.

**Actividad**
* Use *np.array()* para crear una matriz 2D *numpy* a partir de baseball. Nómbralo *np_baseball*.
* Imprime el tipo de *np_baseball*.
* Imprime el *shape* atributo de *np_baseball*. Uso *np_baseball.shape*.

In [1]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


## Datos de béisbol en forma 2D

Tiene otra mirada a los datos de MLB y se da cuenta de que tiene más sentido reestructurar toda esta información en una matriz 2D *numpy*. Este conjunto debe tener 1015 filas, correspondientes a los 1015 jugadores de béisbol sobre los que tiene información, y 2 columnas (para altura y peso).

La MLB fue, nuevamente, muy útil y le pasó los datos en una estructura diferente, una lista de listas de Python. En esta lista de listas, cada sublista representa la altura y el peso de un solo jugador de béisbol. El nombre de esta lista incrustada es baseball.

¿Puede almacenar los datos como una matriz 2D para desbloquear *numpy* la funcionalidad adicional?

**Actividad*

* Use **np.array()** para crear una matriz 2D *numpy* a partir de *baseball*. Nómbralo *np_baseball*.
* Imprime el *shape* atributo de *np_baseball*.

In [29]:
# baseball is available as a regular list of lists
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
baseball = df[['Height(inches)', 'Weight(pounds)']].values.tolist()

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1034, 2)


## Subconjunto de matrices 2D NumPy

Si su matriz 2D *numpy* tiene una estructura regular, es decir, cada fila y columna tiene un número fijo de valores, las formas complicadas de subconjunto se vuelven muy fáciles. Eche un vistazo al siguiente código donde se extraen los elementos **"a"** y **"c"** de una lista de listas.

### regular list of lists
x = [["a", "b"], ["c", "d"]]  
[x[0][0], x[1][0]]

### numpy
import numpy as np  
np_x = np.array(x)  
np_x[:,0]

Para las listas regulares de Python, esto es un verdadero dolor. Sin embargo, para matrices 2D *numpy*, ¡es bastante intuitivo! Los índices antes de la coma se refieren a las filas, mientras que los que siguen a la coma se refieren a las columnas. El :es para rebanar; en este ejemplo, le dice a Python que incluya todas las filas.

El código que convierte la lista *baseball* precargada en una matriz 2D *numpy* ya está en el script. La primera columna contiene la altura de los jugadores en pulgadas y la segunda columna contiene el peso del jugador, en libras. Agregue algunas líneas para hacer las selecciones correctas. ¡Recuerde que en Python, el primer elemento está en el índice 0!

**Actividad**

* Imprima la fila 50 de *np_baseball*.
* Cree una nueva variable, que *np_weight_lb* contenga toda la segunda columna de *np_baseball*.
* Seleccione la altura (primera columna) del 124º jugador de béisbol *np_baseball* e imprímalo.


In [27]:
# baseball is available as a regular list of lists
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
baseball = df[['Height(inches)', 'Weight(pounds)']].values.tolist()

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])

[ 74. 210.]
76.0


## Aritmética 2D

¿Recuerdas cómo calculaste el índice de masa corporal para todos los jugadores de béisbol? *numpy* fue capaz de realizar todos los cálculos por elementos (es decir, elemento por elemento). ¡Para matrices 2D *numpy* esto no es diferente! Puede combinar matrices con números individuales, con vectores y con otras matrices.

Ejecute el código a continuación en el shell de IPython y vea si comprende:

**import numpy as np  
np_mat = np.array([[1, 2],  
                   [3, 4],  
                   [5, 6]])  
np_mat * 2  
np_mat + np.array([10, 10])  
np_mat + np_mat**  

*np_baseball* está codificado para ti; nuevamente es una matriz 2D *numpy* con 3 columnas que representan la altura (en pulgadas), el peso (en libras) y la edad (en años).

**Actividad**

* sume 2 veces *np_baseballe* imprima el resultado.
* Desea convertir las unidades de altura y peso a métricas (metros y kilogramos respectivamente). Como primer paso, crear una matriz *numpy* con tres valores: *0.0254, 0.453592 y 1*. Nombra esta matriz *conversion*.
* Multiplicar *np_baseball* con *conversion* e imprimir el resultado.


In [33]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array
import pandas as pd
df = pd.read_csv("data/mlb_weight_ht.csv")
baseball = df[['Height(inches)', 'Weight(pounds)', 'Age']].values.tolist()

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball+baseball)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

[[148.   360.    45.98]
 [148.   430.    69.38]
 [144.   420.    61.56]
 ...
 [150.   410.    50.38]
 [150.   380.    62.02]
 [146.   390.    55.84]]
[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]
